
Alias:
  Enabled: true

AlignParameters:
  Enabled: true

AndOr:
  Enabled: true

Blocks:
  Enabled: true

BracesAroundHashParameters:
  Enabled: true

CollectionMethods:
  Enabled: true

EmptyLines:
  Enabled: true

EmptyLinesAroundBody:
  Enabled: true

Encoding:
  Enabled: true

HashMethods:
  Enabled: true

HashSyntax:
  Enabled: true

IndentationWidth:
  Enabled: true

Lambda:
  Enabled: true

LeadingCommentSpace:
  Enabled: true

Not:
  Enabled: true

ReduceArguments:
  Enabled: true

SignalException:
  Enabled: true

SpaceAfterComma:
  Enabled: true

SpaceAroundBlockBraces:
  Enabled: true

SpaceAroundEqualsInParameterDefault:
  Enabled: true

SpaceAroundOperators:
  Enabled: true

SpaceInsideBrackets:
  Enabled: true

SpaceInsideHashLiteralBraces:
  Enabled: true

SpaceInsideParens:
  Enabled: true

SpecialGlobalVars:
  Enabled: true

StringLiterals:
  Enabled: true

TrailingBlankLines:
  Enabled: true

TrailingWhitespace:
  Enabled: true

